services:
  db:
    image: postgres:15-alpine
    container_name: ghie-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Tells Docker to check if Postgres is actually accepting connections
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ghie-backend
    env_file:
      - .env
    ports:
      - "8080:10000" # FIXED: Maps host 8080 to container 8080 where Spring Boot is listening
    depends_on:
      db:
        condition: service_healthy # FIXED: Forces backend to wait until DB is fully ready
    environment:
      - SERVER_PORT=10000 # Tells Spring Boot to listen on 10000 inside the container
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING.MAIL.PASSWORD=${SMTP_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - FASTAPI_URL=http://fastapi-service:8000
    volumes:
       # FORMAT : HOST_DIR : CONTAINER_DIR
      - ./uploaded_docs:/app/uploads/supporting_docs/


  fastapi-service:
    build: ./ghie-card-service
    container_name: python-card-service
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pgdata:
  uploaded_docs: